sudo: false  # Use container-based infrastructure
language: python
python:
  - "2.7"
  - "3.4"
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION nose
  - pip install -r requirements.txt
script:
  - nosetests test